concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
jobs:
  cloud-tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      id: minikube
      name: Setup minikube
      uses: manusa/actions-setup-minikube@v2.10.0
      with:
        container runtime: containerd
        driver: docker
        github token: ${{ secrets.GITHUB_TOKEN }}
        kubernetes version: v1.28.1
        minikube version: v1.31.2
        start args: --memory='4gb' --cpus='2'
    - continue-on-error: true
      name: Enable minikube registry
      run: 'minikube addons enable registry

        kubectl port-forward --namespace kube-system service/registry 5000:80 &

        '
    - continue-on-error: true
      name: Cloud Tests - JDK ${{ matrix.java }}
      run: 'mvn clean install -Pcloud-tests -pl resteasy-feature-pack/common,resteasy-feature-pack/galleon-feature-pack,testsuite/cloud-tests
        -amd -am ''-Ddebug.logs'' ''-Pjakarta-staging''

        '
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
        path: '''**/surefire-reports/*''

          ''**/failsafe-reports/*''

          '
    strategy:
      fail-fast: false
      matrix:
        java:
        - '17'
    timeout-minutes: 90
name: RESTEasy Cloud Tests
on:
  repository_dispatch:
    types: trigger-ga___cloud-tests.yml
