jobs:
  resteasy-build:
    needs: wildfly-build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: download-m2
      uses: actions/download-artifact@v4
      with:
        name: wildfly-maven-repository
        path: .
    - continue-on-error: true
      name: Extract Maven Repo
      run: 'tar -xzf wildfly-maven-repository.tar.gz -C ~

        '
      shell: bash
    - continue-on-error: true
      name: Set up JDK ${{ inputs.javaVersion }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ inputs.javaVersion }}
    - continue-on-error: true
      name: Build on ${{ inputs.os }} with Java ${{ inputs.javaVersion }}
      run: mvn clean install '-Dserver.version=${{needs.wildfly-build.outputs.wildfly-version}}'
        '-Pjakarta-staging'
    - continue-on-error: true
      if: failure()
      name: Upload surefire reports
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: '**/surefire-reports/*'
    - continue-on-error: true
      if: failure()
      name: Upload server logs
      uses: actions/upload-artifact@v4
      with:
        name: server-logs
        path: '**/*.log'
  wildfly-build:
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build.yml@main
    with:
      wildfly-branch: ${{ inputs.wildfly-branch }}
      wildfly-repo: ${{ inputs.wildfly-repo }}
name: Manual WildFly Test Build
on:
  repository_dispatch:
    types: trigger-ga___manual-wildfly-build.yml
