concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
jobs:
  additional-profiles:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test with ${{ matrix.profile }} - JDK ${{ matrix.java }}
      run: 'mvn clean install -U -B -fae ${{ matrix.profile }} ''-Dgithub.actions''
        ''-Pjakarta-staging''

        '
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
        path: '**/surefire-reports/*'
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: server-logs-${{ matrix.os }}-${{ matrix.java }}
        path: '**/server.log'
    strategy:
      fail-fast: false
      matrix:
        java:
        - '17'
        - '21'
        profile:
        - -Dsecurity.manager
        - -Dprovision.preview
    timeout-minutes: 90
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven Java ${{ matrix.java }} - ${{ matrix.os }}
      run: 'mvn clean install -U -B -fae ''-Dgithub.actions'' ''-Pjakarta-staging''

        '
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
        path: '**/surefire-reports/*'
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: server-logs-${{ matrix.os }}-${{ matrix.java }}
        path: '**/server.log'
    strategy:
      fail-fast: false
      matrix:
        java:
        - '17'
        - '21'
        os:
        - ubuntu-latest
        - windows-latest
    timeout-minutes: 90
  build-java-docs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build Java Docs with Java 17
      run: 'mvn clean install -B -DskipTests ''-Pjakarta-staging''

        mvn clean site -B -DskipTests ''-Pjakarta-staging''

        '
    timeout-minutes: 20
name: Build and Test RESTEasy
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
