concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
jobs:
  run-tck:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout RESTEasy
      uses: actions/checkout@v4
      with:
        path: resteasy
    - continue-on-error: true
      name: Checkout RESTEasy TCK Runner
      uses: actions/checkout@v4
      with:
        path: resteasy-tck-runner
        repository: resteasy/resteasy-tck-runner
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      id: resteasy-build
      name: Build RESTEasy - JDK ${{ matrix.java }}
      run: 'cd resteasy

        mvn clean install -U -B -fae -DskipTests -Pjakarta-staging

        RESTEASY_VERSION="$(mvn -B help:evaluate -Dexpression=project.version -DforceStdout
        -q)"

        echo "RESTEASY_VERSION=$RESTEASY_VERSION"

        echo "RESTEASY_VERSION=$RESTEASY_VERSION" >> "$GITHUB_OUTPUT"

        '
    - continue-on-error: true
      name: Run the Jakarta REST TCK - JDK ${{ matrix.java }}
      run: 'echo "RESTEASY_VERSION=${{ steps.resteasy-build.outputs.RESTEASY_VERSION
        }}"

        cd resteasy-tck-runner

        mvn clean install -U -B -fae -Dtck.debug.log=true -Dversion.org.jboss.resteasy="${{
        steps.resteasy-build.outputs.RESTEASY_VERSION }}" -Djakarta.staging

        '
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-${{ matrix.os }}-${{ matrix.java }}
        path: '''**/surefire-reports/*''

          ''**/failsafe-reports/*''

          '
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: server-logs-${{ matrix.os }}-${{ matrix.java }}
        path: '**/server.log'
    strategy:
      fail-fast: false
      matrix:
        java:
        - '17'
        - '21'
    timeout-minutes: 90
name: Jakarta REST TCK
on:
  repository_dispatch:
    types: trigger-ga___resteasy-tck.yml
