jobs:
  resteasy-build:
    outputs:
      resteasy-version: ${{ steps.version.outputs.resteasy-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout RESTEasy
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.resteasy-branch }}
        repository: ${{ inputs.resteasy-repo }}
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build RESTEasy
      run: mvn clean install -DskipTests -Dcheckstyle.skip=true -Denforcer.skip=true
        -DskipFormatting=true
    - continue-on-error: true
      id: version
      run: echo "resteasy-version=$(mvn -B help:evaluate -Dexpression=project.version
        -DforceStdout -q)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      name: Archive the repository
      run: 'cd ~

        find ./.m2/repository -type d -name "*SNAPSHOT" -print0 | xargs -0 tar -czf
        ~/resteasy-maven-repository.tar.gz

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: resteasy-maven-repository
        path: ~/resteasy-maven-repository.tar.gz
        retention-days: 5
name: Build RESTEasy Upstream
on:
  repository_dispatch:
    types: trigger-ga___shared-resteasy-build.yml
